targetShapeSpecification = []
genomeMutationRate = 5 # measure in %
rerunsPerAgent = 5
reservoirMutationPercentage = 20
populationSize = 250
survivalRate = 10
maxGenerations = 7500
onlyFinite = False
onlyInfinite = False
boardWidth = 100
boardHeight = boardWidth
startX = int(boardWidth / 2)
startY = int(boardHeight / 2)
printLookupTableOutputs = False
punishForHittingBorder = True
useMidpointsForAspectRatio = True
scaleFitness = False
useReservoirsAsInputs = False
onlyUseSizeAsFitness = False
targetSize = 400
printBoard = False
targetAspectRatio = 3
FILEPATH = "data/t1est" 
useConsistency = True
neighborAssessmentNoise = 0
reservoirAssessmentNoise = 0
genomeLookupNoise = 0
useSignals = True

