import globalVars as globs 
targetShapeSpecification = []
genomeMutationRate = 5 # measure in %
rerunsPerAgent = 3
reservoirMutationPercentage = 20
populationSize = 100 # hp in script
survivalRate = 10
maxGenerations = 7500
onlyFinite = False # hp in script
onlyInfinite = False # hp in script
boardWidth = 100 # hp in script
boardHeight = boardWidth
startX = int(boardWidth / 2)
startY = int(boardHeight / 2)
printLookupTableOutputs = False
punishForHittingBorder = True
useMidpointsForAspectRatio = True
saveAllRunsFromFirstAndLastGenerations = False
scaleFitness = False
useReservoirsAsInputs = False # hp in script
onlyUseSizeAsFitness = False # hp in script
targetSize = 400 # hp in script
printBoard = False
targetAspectRatio = 5 # hp in script
FILEPATH = "data/t1est" 
useConsistency = True # hp in script
neighborAssessmentNoise = 0 # hp in script
reservoirAssessmentNoise = 0 # hp in script
genomeLookupNoise = 0 # hp in script
useSignals = True # hp in script